use Company_SD

--1
select *  FROM EMPLOYEE 

--2
SELECT FNAME, LNAME, SALARY, DNO
FROM EMPLOYEE

--3
SELECT PNAME, PLOCATION, DNUM
FROM PROJECT

--4
SELECT  Fname +' '+ Lname AS full_name,
    Salary * 0.10* 12 AS ANNUAL_COMM
FROM 
    Employee;

	--5
	SELECT SSN , FNAME, Salary as MONTHLY_SALARY 
	FROM EMPLOYEE
	WHERE SALARY >1000

	--6
	SELECT SSN , FNAME, (Salary*12) as ANN_SALARY
	FROM EMPLOYEE
	WHERE (SALARY*12)>1000

	--7
	SELECT FNAME, SALARY
	FROM EMPLOYEE
	WHERE SEX='F'

	--8
	SELECT Dname, Dnum
	FROM Departments
	WHERE MGRSSN=968574

	--9
	SELECT PNUMBER, PNAME, PLOCATION
	FROM PROJECT
	WHERE DNUM=10